server:
  port: 8082

spring:
  application:
    name: linlang-memeber
  ##数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/linlangmember?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    name: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: SearchHikariCP
      max-lifetime: 1800000
      connection-timeout: 3000
      connection-test-query: SELECT 1 FROM DUAL